/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nowireless_imaqdx_IMAQdx_IMAQdxBusType */

#ifndef _Included_org_nowireless_imaqdx_IMAQdx_IMAQdxBusType
#define _Included_org_nowireless_imaqdx_IMAQdx_IMAQdxBusType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
