/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nowireless_imaqdx_IMAQdx */

#ifndef _Included_org_nowireless_imaqdx_IMAQdx
#define _Included_org_nowireless_imaqdx_IMAQdx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nowireless_imaqdx_IMAQdx
 * Method:    _IMAQdxEnumerateCameras
 * Signature: (JLjava/nio/ByteBuffer;Z)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx__1IMAQdxEnumerateCameras
  (JNIEnv *, jclass, jlong, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
