/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformationArray */

#ifndef _Included_org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformationArray
#define _Included_org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformationArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformationArray
 * Method:    _allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformationArray__1allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformationArray
 * Method:    _get
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformationArray__1get
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
