/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation */

#ifndef _Included_org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
#define _Included_org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1type
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1version
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1flags
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _serialNumberHi
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1serialNumberHi
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _serialNumberLo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1serialNumberLo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _busType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1busType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _interfaceName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1interfaceName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _vendorName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1vendorName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _modelName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1modelName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _cameraFileName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1cameraFileName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_nowireless_imaqdx_IMAQdx_IMAQdxCameraInformation
 * Method:    _cameraAttributeUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nowireless_imaqdx_IMAQdx_00024IMAQdxCameraInformation__1cameraAttributeUrl
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
